[features]
seeds = false
skip-lint = false
[programs.localnet]
wba_vault = "VG58thf3atpUtDia6NUiJJeJLuHMy2z5CRiTBPXLzwT"
escrow = "KRKA3ugDP5iE79zDuLQEs6qCvY7eSRYbS94vgsTgRU2"
feedback = "FEEDLQWp85GJBrum4ASAR6WEAW595oQfaST1N84HZFbS"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/dev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/feedback.ts"
